/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HCL
 */
public class LOGINFORMB extends javax.swing.JFrame {

    /**
     * Creates new form LOGINFORMB
     */
    public LOGINFORMB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        COMBINED = new javax.swing.JButton();
        CUST_UPD = new javax.swing.JButton();
        PROD_UPD = new javax.swing.JButton();
        ORDER_SEARCH = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EMP_UPD = new javax.swing.JButton();
        PROD_SEARCH = new javax.swing.JButton();
        EMP_SEARCH = new javax.swing.JButton();
        ORDER_UPD = new javax.swing.JButton();
        CUST_SEARCH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        COMBINED.setText("COMBINED FORMS");
        COMBINED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBINEDActionPerformed(evt);
            }
        });

        CUST_UPD.setText("CUSTOMER");
        CUST_UPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUST_UPDActionPerformed(evt);
            }
        });

        PROD_UPD.setText("PRODUCTS");
        PROD_UPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROD_UPDActionPerformed(evt);
            }
        });

        ORDER_SEARCH.setText("ORDER");
        ORDER_SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORDER_SEARCHActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("MULTIPLE FORMS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("UPDATE FORMS");

        EMP_UPD.setText("EMPLOYEE");
        EMP_UPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMP_UPDActionPerformed(evt);
            }
        });

        PROD_SEARCH.setText("PRODUCTS");
        PROD_SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROD_SEARCHActionPerformed(evt);
            }
        });

        EMP_SEARCH.setText("EMPLOYEE");
        EMP_SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMP_SEARCHActionPerformed(evt);
            }
        });

        ORDER_UPD.setText("ORDER");
        ORDER_UPD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORDER_UPDActionPerformed(evt);
            }
        });

        CUST_SEARCH.setText("CUSTOMER");
        CUST_SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUST_SEARCHActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("SEARCH FORMS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PROD_SEARCH)
                            .addComponent(EMP_SEARCH)
                            .addComponent(CUST_SEARCH)
                            .addComponent(ORDER_SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EMP_UPD)
                            .addComponent(PROD_UPD)
                            .addComponent(CUST_UPD)
                            .addComponent(ORDER_UPD, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(COMBINED)
                    .addComponent(jLabel3))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PROD_SEARCH)
                            .addComponent(PROD_UPD))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EMP_SEARCH)
                            .addComponent(EMP_UPD)
                            .addComponent(COMBINED))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CUST_SEARCH)
                            .addComponent(CUST_UPD))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ORDER_SEARCH)
                            .addComponent(ORDER_UPD)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(456, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PROD_UPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROD_UPDActionPerformed
PRODUCTUPDATEFORM a=new PRODUCTUPDATEFORM();
a.setVisible(true);
this.dispose();        
    }//GEN-LAST:event_PROD_UPDActionPerformed

    private void PROD_SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROD_SEARCHActionPerformed
PRODUCTSEARCHFORM a=new PRODUCTSEARCHFORM();
a.setVisible(true);
      
    }//GEN-LAST:event_PROD_SEARCHActionPerformed

    private void EMP_SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMP_SEARCHActionPerformed
EMPLOYEESEARCHFORM a=new EMPLOYEESEARCHFORM();
a.setVisible(true);
this.dispose();       
    }//GEN-LAST:event_EMP_SEARCHActionPerformed

    private void CUST_SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUST_SEARCHActionPerformed
CUSTOMERSEARCHFORM a=new CUSTOMERSEARCHFORM();
a.setVisible(true);
this.dispose();       
    }//GEN-LAST:event_CUST_SEARCHActionPerformed

    private void ORDER_SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORDER_SEARCHActionPerformed
ORDERSEARCHFORM a=new ORDERSEARCHFORM();
a.setVisible(true);
this.dispose();        
    }//GEN-LAST:event_ORDER_SEARCHActionPerformed

    private void EMP_UPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMP_UPDActionPerformed
EMPLOYEEUPDATEFORM a=new EMPLOYEEUPDATEFORM();
a.setVisible(true);
this.dispose();        
    }//GEN-LAST:event_EMP_UPDActionPerformed

    private void CUST_UPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUST_UPDActionPerformed
CUSTOMERUPDATEFORM a=new CUSTOMERUPDATEFORM();
a.setVisible(true);
this.dispose();       
    }//GEN-LAST:event_CUST_UPDActionPerformed

    private void ORDER_UPDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORDER_UPDActionPerformed
ORDERUPDATEFORM a=new ORDERUPDATEFORM();
a.setVisible(true);
this.dispose();        
    }//GEN-LAST:event_ORDER_UPDActionPerformed

    private void COMBINEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBINEDActionPerformed
COMBINEDFORM a=new COMBINEDFORM();
a.setVisible(true);
this.dispose();       
    }//GEN-LAST:event_COMBINEDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGINFORMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGINFORMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGINFORMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGINFORMB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGINFORMB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton COMBINED;
    public javax.swing.JButton CUST_SEARCH;
    public javax.swing.JButton CUST_UPD;
    public javax.swing.JButton EMP_SEARCH;
    public javax.swing.JButton EMP_UPD;
    public javax.swing.JButton ORDER_SEARCH;
    public javax.swing.JButton ORDER_UPD;
    public javax.swing.JButton PROD_SEARCH;
    public javax.swing.JButton PROD_UPD;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
